In [1]:
import pandas as pd

In [29]:
df = pd.read_csv('Data_emp.csv')
df

   emp_id name  salary dept_name country
0       1    A     200        IT     USA
1       2    B     100        HR   India
2       3    C     400        IT   India
3       4    D     500        IT   India
4       5    E     400        HR   India
5       6    F     600     Admin     USA
6       7    G     700        IT     USA
7       8  NaN     100       NaN     NaN
8       9    J     500       NaN     USA
9       1    A     200        IT     USA

In [13]:
dup = df[df.duplicated()]

In [14]:
dup

   emp_id name  salary dept_name country
9       1    A     200        IT     USA

In [19]:
g = df.groupby('dept_name')

In [30]:
g['emp_id'].count()

dept_name
Admin    1
HR       2
IT       5
Name: emp_id, dtype: int64

In [59]:
df.count()

NameError: name 'notnull' is not defined